name: Schedule Tests - PR

on:
  schedule:
    - cron:  '0 20 * * 5'

jobs:
  RunTest:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar o projeto
        uses: actions/checkout@v4

      - name: Instalar Java 11
        uses: actions/checkout@v4
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: 'maven'

      - name: Instalar FireFox
        uses: browser-actions/setup-firefox@v1

      - name: Instalar o GeckoDriver
        uses: browser-actions/setup-geckodriver@latest

      - name: Run Test
        run: mvn test -Dtest=RunCucumber -Dbrowser=firefox-ci -Dcucumber.options="--tags ~@Ignore"

      - name: Gerar relatórios
        if: always()
        run: mvn cluecumber-report:reporting

      - name: Arquivar relatórios
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: report-tests
          path: '**/formated-report/'

      - name: Enviar Notificação Slack - Sucesso
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://imagepng.org/wp-content/uploads/2019/12/check-icone-scaled.png
          SLACK_MESSAGE: "Sucesso na excução de testes agendados"
          SLACK_TITLE: "Teste com Sucesso"
          SLACK_USERNAME: SUCESSO

      - name: Enviar Notificação Slack - Falha
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://www.pngwing.com/pt/free-png-vohup
          SLACK_MESSAGE: "Falha na excução de testes agendados"
          SLACK_TITLE: "Teste com Falha"
          SLACK_USERNAME: FALHA